/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StatusesService } from "../statuses.service";
import { StatusesCreateInput } from "./StatusesCreateInput";
import { Statuses } from "./Statuses";
import { StatusesFindManyArgs } from "./StatusesFindManyArgs";
import { StatusesWhereUniqueInput } from "./StatusesWhereUniqueInput";
import { StatusesUpdateInput } from "./StatusesUpdateInput";
import { ProjectsFindManyArgs } from "../../projects/base/ProjectsFindManyArgs";
import { Projects } from "../../projects/base/Projects";
import { ProjectsWhereUniqueInput } from "../../projects/base/ProjectsWhereUniqueInput";

export class StatusesControllerBase {
  constructor(protected readonly service: StatusesService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Statuses })
  async createStatuses(
    @common.Body() data: StatusesCreateInput
  ): Promise<Statuses> {
    return await this.service.createStatuses({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Statuses] })
  @ApiNestedQuery(StatusesFindManyArgs)
  async statusesItems(@common.Req() request: Request): Promise<Statuses[]> {
    const args = plainToClass(StatusesFindManyArgs, request.query);
    return this.service.statusesItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Statuses })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async statuses(
    @common.Param() params: StatusesWhereUniqueInput
  ): Promise<Statuses | null> {
    const result = await this.service.statuses({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Statuses })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStatuses(
    @common.Param() params: StatusesWhereUniqueInput,
    @common.Body() data: StatusesUpdateInput
  ): Promise<Statuses | null> {
    try {
      return await this.service.updateStatuses({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Statuses })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStatuses(
    @common.Param() params: StatusesWhereUniqueInput
  ): Promise<Statuses | null> {
    try {
      return await this.service.deleteStatuses({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/projectsItems")
  @ApiNestedQuery(ProjectsFindManyArgs)
  async findProjectsItems(
    @common.Req() request: Request,
    @common.Param() params: StatusesWhereUniqueInput
  ): Promise<Projects[]> {
    const query = plainToClass(ProjectsFindManyArgs, request.query);
    const results = await this.service.findProjectsItems(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        service: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        status: {
          select: {
            id: true,
          },
        },

        request: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/projectsItems")
  async connectProjectsItems(
    @common.Param() params: StatusesWhereUniqueInput,
    @common.Body() body: ProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectsItems: {
        connect: body,
      },
    };
    await this.service.updateStatuses({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/projectsItems")
  async updateProjectsItems(
    @common.Param() params: StatusesWhereUniqueInput,
    @common.Body() body: ProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectsItems: {
        set: body,
      },
    };
    await this.service.updateStatuses({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/projectsItems")
  async disconnectProjectsItems(
    @common.Param() params: StatusesWhereUniqueInput,
    @common.Body() body: ProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectsItems: {
        disconnect: body,
      },
    };
    await this.service.updateStatuses({
      where: params,
      data,
      select: { id: true },
    });
  }
}
