/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Services } from "./Services";
import { ServicesCountArgs } from "./ServicesCountArgs";
import { ServicesFindManyArgs } from "./ServicesFindManyArgs";
import { ServicesFindUniqueArgs } from "./ServicesFindUniqueArgs";
import { CreateServicesArgs } from "./CreateServicesArgs";
import { UpdateServicesArgs } from "./UpdateServicesArgs";
import { DeleteServicesArgs } from "./DeleteServicesArgs";
import { ProjectsFindManyArgs } from "../../projects/base/ProjectsFindManyArgs";
import { Projects } from "../../projects/base/Projects";
import { TasksFindManyArgs } from "../../tasks/base/TasksFindManyArgs";
import { Tasks } from "../../tasks/base/Tasks";
import { ServicesService } from "../services.service";
@graphql.Resolver(() => Services)
export class ServicesResolverBase {
  constructor(protected readonly service: ServicesService) {}

  async _servicesItemsMeta(
    @graphql.Args() args: ServicesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Services])
  async servicesItems(
    @graphql.Args() args: ServicesFindManyArgs
  ): Promise<Services[]> {
    return this.service.servicesItems(args);
  }

  @graphql.Query(() => Services, { nullable: true })
  async services(
    @graphql.Args() args: ServicesFindUniqueArgs
  ): Promise<Services | null> {
    const result = await this.service.services(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Services)
  async createServices(
    @graphql.Args() args: CreateServicesArgs
  ): Promise<Services> {
    return await this.service.createServices({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Services)
  async updateServices(
    @graphql.Args() args: UpdateServicesArgs
  ): Promise<Services | null> {
    try {
      return await this.service.updateServices({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Services)
  async deleteServices(
    @graphql.Args() args: DeleteServicesArgs
  ): Promise<Services | null> {
    try {
      return await this.service.deleteServices(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Projects], { name: "projectsItems" })
  async findProjectsItems(
    @graphql.Parent() parent: Services,
    @graphql.Args() args: ProjectsFindManyArgs
  ): Promise<Projects[]> {
    const results = await this.service.findProjectsItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Tasks], { name: "tasksItems" })
  async findTasksItems(
    @graphql.Parent() parent: Services,
    @graphql.Args() args: TasksFindManyArgs
  ): Promise<Tasks[]> {
    const results = await this.service.findTasksItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
