/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ServicesService } from "../services.service";
import { ServicesCreateInput } from "./ServicesCreateInput";
import { Services } from "./Services";
import { ServicesFindManyArgs } from "./ServicesFindManyArgs";
import { ServicesWhereUniqueInput } from "./ServicesWhereUniqueInput";
import { ServicesUpdateInput } from "./ServicesUpdateInput";
import { ProjectsFindManyArgs } from "../../projects/base/ProjectsFindManyArgs";
import { Projects } from "../../projects/base/Projects";
import { ProjectsWhereUniqueInput } from "../../projects/base/ProjectsWhereUniqueInput";
import { TasksFindManyArgs } from "../../tasks/base/TasksFindManyArgs";
import { Tasks } from "../../tasks/base/Tasks";
import { TasksWhereUniqueInput } from "../../tasks/base/TasksWhereUniqueInput";

export class ServicesControllerBase {
  constructor(protected readonly service: ServicesService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Services })
  async createServices(
    @common.Body() data: ServicesCreateInput
  ): Promise<Services> {
    return await this.service.createServices({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Services] })
  @ApiNestedQuery(ServicesFindManyArgs)
  async servicesItems(@common.Req() request: Request): Promise<Services[]> {
    const args = plainToClass(ServicesFindManyArgs, request.query);
    return this.service.servicesItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Services })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async services(
    @common.Param() params: ServicesWhereUniqueInput
  ): Promise<Services | null> {
    const result = await this.service.services({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Services })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateServices(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() data: ServicesUpdateInput
  ): Promise<Services | null> {
    try {
      return await this.service.updateServices({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Services })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteServices(
    @common.Param() params: ServicesWhereUniqueInput
  ): Promise<Services | null> {
    try {
      return await this.service.deleteServices({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/projectsItems")
  @ApiNestedQuery(ProjectsFindManyArgs)
  async findProjectsItems(
    @common.Req() request: Request,
    @common.Param() params: ServicesWhereUniqueInput
  ): Promise<Projects[]> {
    const query = plainToClass(ProjectsFindManyArgs, request.query);
    const results = await this.service.findProjectsItems(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        service: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        status: {
          select: {
            id: true,
          },
        },

        request: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/projectsItems")
  async connectProjectsItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: ProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectsItems: {
        connect: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/projectsItems")
  async updateProjectsItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: ProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectsItems: {
        set: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/projectsItems")
  async disconnectProjectsItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: ProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectsItems: {
        disconnect: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/tasksItems")
  @ApiNestedQuery(TasksFindManyArgs)
  async findTasksItems(
    @common.Req() request: Request,
    @common.Param() params: ServicesWhereUniqueInput
  ): Promise<Tasks[]> {
    const query = plainToClass(TasksFindManyArgs, request.query);
    const results = await this.service.findTasksItems(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        service: {
          select: {
            id: true,
          },
        },

        developmentStage: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tasksItems")
  async connectTasksItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: TasksWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tasksItems: {
        connect: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tasksItems")
  async updateTasksItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: TasksWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tasksItems: {
        set: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tasksItems")
  async disconnectTasksItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: TasksWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tasksItems: {
        disconnect: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }
}
