/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProjectsService } from "../projects.service";
import { ProjectsCreateInput } from "./ProjectsCreateInput";
import { Projects } from "./Projects";
import { ProjectsFindManyArgs } from "./ProjectsFindManyArgs";
import { ProjectsWhereUniqueInput } from "./ProjectsWhereUniqueInput";
import { ProjectsUpdateInput } from "./ProjectsUpdateInput";
import { EmployeeProjectsFindManyArgs } from "../../employeeProjects/base/EmployeeProjectsFindManyArgs";
import { EmployeeProjects } from "../../employeeProjects/base/EmployeeProjects";
import { EmployeeProjectsWhereUniqueInput } from "../../employeeProjects/base/EmployeeProjectsWhereUniqueInput";

export class ProjectsControllerBase {
  constructor(protected readonly service: ProjectsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Projects })
  async createProjects(
    @common.Body() data: ProjectsCreateInput
  ): Promise<Projects> {
    return await this.service.createProjects({
      data: {
        ...data,

        service: data.service
          ? {
              connect: data.service,
            }
          : undefined,

        client: data.client
          ? {
              connect: data.client,
            }
          : undefined,

        status: data.status
          ? {
              connect: data.status,
            }
          : undefined,

        request: data.request
          ? {
              connect: data.request,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        service: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        status: {
          select: {
            id: true,
          },
        },

        request: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Projects] })
  @ApiNestedQuery(ProjectsFindManyArgs)
  async projectsItems(@common.Req() request: Request): Promise<Projects[]> {
    const args = plainToClass(ProjectsFindManyArgs, request.query);
    return this.service.projectsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        service: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        status: {
          select: {
            id: true,
          },
        },

        request: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Projects })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async projects(
    @common.Param() params: ProjectsWhereUniqueInput
  ): Promise<Projects | null> {
    const result = await this.service.projects({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        service: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        status: {
          select: {
            id: true,
          },
        },

        request: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Projects })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProjects(
    @common.Param() params: ProjectsWhereUniqueInput,
    @common.Body() data: ProjectsUpdateInput
  ): Promise<Projects | null> {
    try {
      return await this.service.updateProjects({
        where: params,
        data: {
          ...data,

          service: data.service
            ? {
                connect: data.service,
              }
            : undefined,

          client: data.client
            ? {
                connect: data.client,
              }
            : undefined,

          status: data.status
            ? {
                connect: data.status,
              }
            : undefined,

          request: data.request
            ? {
                connect: data.request,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          service: {
            select: {
              id: true,
            },
          },

          client: {
            select: {
              id: true,
            },
          },

          status: {
            select: {
              id: true,
            },
          },

          request: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Projects })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProjects(
    @common.Param() params: ProjectsWhereUniqueInput
  ): Promise<Projects | null> {
    try {
      return await this.service.deleteProjects({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          service: {
            select: {
              id: true,
            },
          },

          client: {
            select: {
              id: true,
            },
          },

          status: {
            select: {
              id: true,
            },
          },

          request: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/employeeProjectsItems")
  @ApiNestedQuery(EmployeeProjectsFindManyArgs)
  async findEmployeeProjectsItems(
    @common.Req() request: Request,
    @common.Param() params: ProjectsWhereUniqueInput
  ): Promise<EmployeeProjects[]> {
    const query = plainToClass(EmployeeProjectsFindManyArgs, request.query);
    const results = await this.service.findEmployeeProjectsItems(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        project: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/employeeProjectsItems")
  async connectEmployeeProjectsItems(
    @common.Param() params: ProjectsWhereUniqueInput,
    @common.Body() body: EmployeeProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employeeProjectsItems: {
        connect: body,
      },
    };
    await this.service.updateProjects({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/employeeProjectsItems")
  async updateEmployeeProjectsItems(
    @common.Param() params: ProjectsWhereUniqueInput,
    @common.Body() body: EmployeeProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employeeProjectsItems: {
        set: body,
      },
    };
    await this.service.updateProjects({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/employeeProjectsItems")
  async disconnectEmployeeProjectsItems(
    @common.Param() params: ProjectsWhereUniqueInput,
    @common.Body() body: EmployeeProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employeeProjectsItems: {
        disconnect: body,
      },
    };
    await this.service.updateProjects({
      where: params,
      data,
      select: { id: true },
    });
  }
}
