/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EmployeeProjectsUpdateManyWithoutProjectsItemsInput } from "./EmployeeProjectsUpdateManyWithoutProjectsItemsInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { ServicesWhereUniqueInput } from "../../services/base/ServicesWhereUniqueInput";
import { ClientsWhereUniqueInput } from "../../clients/base/ClientsWhereUniqueInput";
import { StatusesWhereUniqueInput } from "../../statuses/base/StatusesWhereUniqueInput";
import { RequestsWhereUniqueInput } from "../../requests/base/RequestsWhereUniqueInput";

@InputType()
class ProjectsUpdateInput {
  @ApiProperty({
    required: false,
    type: () => EmployeeProjectsUpdateManyWithoutProjectsItemsInput,
  })
  @ValidateNested()
  @Type(() => EmployeeProjectsUpdateManyWithoutProjectsItemsInput)
  @IsOptional()
  @Field(() => EmployeeProjectsUpdateManyWithoutProjectsItemsInput, {
    nullable: true,
  })
  employeeProjectsItems?: EmployeeProjectsUpdateManyWithoutProjectsItemsInput;

  @ApiProperty({
    required: false,
    type: () => ServicesWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServicesWhereUniqueInput)
  @IsOptional()
  @Field(() => ServicesWhereUniqueInput, {
    nullable: true,
  })
  service?: ServicesWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ClientsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClientsWhereUniqueInput)
  @IsOptional()
  @Field(() => ClientsWhereUniqueInput, {
    nullable: true,
  })
  client?: ClientsWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => StatusesWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => StatusesWhereUniqueInput)
  @IsOptional()
  @Field(() => StatusesWhereUniqueInput, {
    nullable: true,
  })
  status?: StatusesWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => RequestsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RequestsWhereUniqueInput)
  @IsOptional()
  @Field(() => RequestsWhereUniqueInput, {
    nullable: true,
  })
  request?: RequestsWhereUniqueInput | null;
}

export { ProjectsUpdateInput as ProjectsUpdateInput };
