/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Projects } from "./Projects";
import { ProjectsCountArgs } from "./ProjectsCountArgs";
import { ProjectsFindManyArgs } from "./ProjectsFindManyArgs";
import { ProjectsFindUniqueArgs } from "./ProjectsFindUniqueArgs";
import { CreateProjectsArgs } from "./CreateProjectsArgs";
import { UpdateProjectsArgs } from "./UpdateProjectsArgs";
import { DeleteProjectsArgs } from "./DeleteProjectsArgs";
import { EmployeeProjectsFindManyArgs } from "../../employeeProjects/base/EmployeeProjectsFindManyArgs";
import { EmployeeProjects } from "../../employeeProjects/base/EmployeeProjects";
import { Services } from "../../services/base/Services";
import { Clients } from "../../clients/base/Clients";
import { Statuses } from "../../statuses/base/Statuses";
import { Requests } from "../../requests/base/Requests";
import { ProjectsService } from "../projects.service";
@graphql.Resolver(() => Projects)
export class ProjectsResolverBase {
  constructor(protected readonly service: ProjectsService) {}

  async _projectsItemsMeta(
    @graphql.Args() args: ProjectsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Projects])
  async projectsItems(
    @graphql.Args() args: ProjectsFindManyArgs
  ): Promise<Projects[]> {
    return this.service.projectsItems(args);
  }

  @graphql.Query(() => Projects, { nullable: true })
  async projects(
    @graphql.Args() args: ProjectsFindUniqueArgs
  ): Promise<Projects | null> {
    const result = await this.service.projects(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Projects)
  async createProjects(
    @graphql.Args() args: CreateProjectsArgs
  ): Promise<Projects> {
    return await this.service.createProjects({
      ...args,
      data: {
        ...args.data,

        service: args.data.service
          ? {
              connect: args.data.service,
            }
          : undefined,

        client: args.data.client
          ? {
              connect: args.data.client,
            }
          : undefined,

        status: args.data.status
          ? {
              connect: args.data.status,
            }
          : undefined,

        request: args.data.request
          ? {
              connect: args.data.request,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Projects)
  async updateProjects(
    @graphql.Args() args: UpdateProjectsArgs
  ): Promise<Projects | null> {
    try {
      return await this.service.updateProjects({
        ...args,
        data: {
          ...args.data,

          service: args.data.service
            ? {
                connect: args.data.service,
              }
            : undefined,

          client: args.data.client
            ? {
                connect: args.data.client,
              }
            : undefined,

          status: args.data.status
            ? {
                connect: args.data.status,
              }
            : undefined,

          request: args.data.request
            ? {
                connect: args.data.request,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Projects)
  async deleteProjects(
    @graphql.Args() args: DeleteProjectsArgs
  ): Promise<Projects | null> {
    try {
      return await this.service.deleteProjects(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [EmployeeProjects], {
    name: "employeeProjectsItems",
  })
  async findEmployeeProjectsItems(
    @graphql.Parent() parent: Projects,
    @graphql.Args() args: EmployeeProjectsFindManyArgs
  ): Promise<EmployeeProjects[]> {
    const results = await this.service.findEmployeeProjectsItems(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Services, {
    nullable: true,
    name: "service",
  })
  async getService(
    @graphql.Parent() parent: Projects
  ): Promise<Services | null> {
    const result = await this.service.getService(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Clients, {
    nullable: true,
    name: "client",
  })
  async getClient(@graphql.Parent() parent: Projects): Promise<Clients | null> {
    const result = await this.service.getClient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Statuses, {
    nullable: true,
    name: "status",
  })
  async getStatus(
    @graphql.Parent() parent: Projects
  ): Promise<Statuses | null> {
    const result = await this.service.getStatus(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Requests, {
    nullable: true,
    name: "request",
  })
  async getRequest(
    @graphql.Parent() parent: Projects
  ): Promise<Requests | null> {
    const result = await this.service.getRequest(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
