/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Chats } from "./Chats";
import { ChatsCountArgs } from "./ChatsCountArgs";
import { ChatsFindManyArgs } from "./ChatsFindManyArgs";
import { ChatsFindUniqueArgs } from "./ChatsFindUniqueArgs";
import { DeleteChatsArgs } from "./DeleteChatsArgs";
import { ChatsService } from "../chats.service";
@graphql.Resolver(() => Chats)
export class ChatsResolverBase {
  constructor(protected readonly service: ChatsService) {}

  async _chatsItemsMeta(
    @graphql.Args() args: ChatsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Chats])
  async chatsItems(@graphql.Args() args: ChatsFindManyArgs): Promise<Chats[]> {
    return this.service.chatsItems(args);
  }

  @graphql.Query(() => Chats, { nullable: true })
  async chats(
    @graphql.Args() args: ChatsFindUniqueArgs
  ): Promise<Chats | null> {
    const result = await this.service.chats(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Chats)
  async deleteChats(
    @graphql.Args() args: DeleteChatsArgs
  ): Promise<Chats | null> {
    try {
      return await this.service.deleteChats(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
