/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Clients } from "./Clients";
import { ClientsCountArgs } from "./ClientsCountArgs";
import { ClientsFindManyArgs } from "./ClientsFindManyArgs";
import { ClientsFindUniqueArgs } from "./ClientsFindUniqueArgs";
import { CreateClientsArgs } from "./CreateClientsArgs";
import { UpdateClientsArgs } from "./UpdateClientsArgs";
import { DeleteClientsArgs } from "./DeleteClientsArgs";
import { ProjectsFindManyArgs } from "../../projects/base/ProjectsFindManyArgs";
import { Projects } from "../../projects/base/Projects";
import { User } from "../../user/base/User";
import { ClientsService } from "../clients.service";
@graphql.Resolver(() => Clients)
export class ClientsResolverBase {
  constructor(protected readonly service: ClientsService) {}

  async _clientsItemsMeta(
    @graphql.Args() args: ClientsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Clients])
  async clientsItems(
    @graphql.Args() args: ClientsFindManyArgs
  ): Promise<Clients[]> {
    return this.service.clientsItems(args);
  }

  @graphql.Query(() => Clients, { nullable: true })
  async clients(
    @graphql.Args() args: ClientsFindUniqueArgs
  ): Promise<Clients | null> {
    const result = await this.service.clients(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Clients)
  async createClients(
    @graphql.Args() args: CreateClientsArgs
  ): Promise<Clients> {
    return await this.service.createClients({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Clients)
  async updateClients(
    @graphql.Args() args: UpdateClientsArgs
  ): Promise<Clients | null> {
    try {
      return await this.service.updateClients({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Clients)
  async deleteClients(
    @graphql.Args() args: DeleteClientsArgs
  ): Promise<Clients | null> {
    try {
      return await this.service.deleteClients(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Projects], { name: "projectsItems" })
  async findProjectsItems(
    @graphql.Parent() parent: Clients,
    @graphql.Args() args: ProjectsFindManyArgs
  ): Promise<Projects[]> {
    const results = await this.service.findProjectsItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Clients): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
