/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ClientsService } from "../clients.service";
import { ClientsCreateInput } from "./ClientsCreateInput";
import { Clients } from "./Clients";
import { ClientsFindManyArgs } from "./ClientsFindManyArgs";
import { ClientsWhereUniqueInput } from "./ClientsWhereUniqueInput";
import { ClientsUpdateInput } from "./ClientsUpdateInput";
import { ProjectsFindManyArgs } from "../../projects/base/ProjectsFindManyArgs";
import { Projects } from "../../projects/base/Projects";
import { ProjectsWhereUniqueInput } from "../../projects/base/ProjectsWhereUniqueInput";

export class ClientsControllerBase {
  constructor(protected readonly service: ClientsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Clients })
  async createClients(
    @common.Body() data: ClientsCreateInput
  ): Promise<Clients> {
    return await this.service.createClients({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Clients] })
  @ApiNestedQuery(ClientsFindManyArgs)
  async clientsItems(@common.Req() request: Request): Promise<Clients[]> {
    const args = plainToClass(ClientsFindManyArgs, request.query);
    return this.service.clientsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Clients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async clients(
    @common.Param() params: ClientsWhereUniqueInput
  ): Promise<Clients | null> {
    const result = await this.service.clients({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Clients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateClients(
    @common.Param() params: ClientsWhereUniqueInput,
    @common.Body() data: ClientsUpdateInput
  ): Promise<Clients | null> {
    try {
      return await this.service.updateClients({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Clients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteClients(
    @common.Param() params: ClientsWhereUniqueInput
  ): Promise<Clients | null> {
    try {
      return await this.service.deleteClients({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/projectsItems")
  @ApiNestedQuery(ProjectsFindManyArgs)
  async findProjectsItems(
    @common.Req() request: Request,
    @common.Param() params: ClientsWhereUniqueInput
  ): Promise<Projects[]> {
    const query = plainToClass(ProjectsFindManyArgs, request.query);
    const results = await this.service.findProjectsItems(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        service: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        status: {
          select: {
            id: true,
          },
        },

        request: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/projectsItems")
  async connectProjectsItems(
    @common.Param() params: ClientsWhereUniqueInput,
    @common.Body() body: ProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectsItems: {
        connect: body,
      },
    };
    await this.service.updateClients({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/projectsItems")
  async updateProjectsItems(
    @common.Param() params: ClientsWhereUniqueInput,
    @common.Body() body: ProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectsItems: {
        set: body,
      },
    };
    await this.service.updateClients({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/projectsItems")
  async disconnectProjectsItems(
    @common.Param() params: ClientsWhereUniqueInput,
    @common.Body() body: ProjectsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectsItems: {
        disconnect: body,
      },
    };
    await this.service.updateClients({
      where: params,
      data,
      select: { id: true },
    });
  }
}
