/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Messages } from "./Messages";
import { MessagesCountArgs } from "./MessagesCountArgs";
import { MessagesFindManyArgs } from "./MessagesFindManyArgs";
import { MessagesFindUniqueArgs } from "./MessagesFindUniqueArgs";
import { DeleteMessagesArgs } from "./DeleteMessagesArgs";
import { MessagesService } from "../messages.service";
@graphql.Resolver(() => Messages)
export class MessagesResolverBase {
  constructor(protected readonly service: MessagesService) {}

  async _messagesItemsMeta(
    @graphql.Args() args: MessagesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Messages])
  async messagesItems(
    @graphql.Args() args: MessagesFindManyArgs
  ): Promise<Messages[]> {
    return this.service.messagesItems(args);
  }

  @graphql.Query(() => Messages, { nullable: true })
  async messages(
    @graphql.Args() args: MessagesFindUniqueArgs
  ): Promise<Messages | null> {
    const result = await this.service.messages(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Messages)
  async deleteMessages(
    @graphql.Args() args: DeleteMessagesArgs
  ): Promise<Messages | null> {
    try {
      return await this.service.deleteMessages(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
