/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { EmployeeProjectsUpdateManyWithoutEmployeesItemsInput } from "./EmployeeProjectsUpdateManyWithoutEmployeesItemsInput";
import { EmployeeRolesUpdateManyWithoutEmployeesItemsInput } from "./EmployeeRolesUpdateManyWithoutEmployeesItemsInput";
import { EmployeeTasksUpdateManyWithoutEmployeesItemsInput } from "./EmployeeTasksUpdateManyWithoutEmployeesItemsInput";

@InputType()
class EmployeesUpdateInput {
  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => EmployeeProjectsUpdateManyWithoutEmployeesItemsInput,
  })
  @ValidateNested()
  @Type(() => EmployeeProjectsUpdateManyWithoutEmployeesItemsInput)
  @IsOptional()
  @Field(() => EmployeeProjectsUpdateManyWithoutEmployeesItemsInput, {
    nullable: true,
  })
  employeeProjectsItems?: EmployeeProjectsUpdateManyWithoutEmployeesItemsInput;

  @ApiProperty({
    required: false,
    type: () => EmployeeRolesUpdateManyWithoutEmployeesItemsInput,
  })
  @ValidateNested()
  @Type(() => EmployeeRolesUpdateManyWithoutEmployeesItemsInput)
  @IsOptional()
  @Field(() => EmployeeRolesUpdateManyWithoutEmployeesItemsInput, {
    nullable: true,
  })
  employeeRolesItems?: EmployeeRolesUpdateManyWithoutEmployeesItemsInput;

  @ApiProperty({
    required: false,
    type: () => EmployeeTasksUpdateManyWithoutEmployeesItemsInput,
  })
  @ValidateNested()
  @Type(() => EmployeeTasksUpdateManyWithoutEmployeesItemsInput)
  @IsOptional()
  @Field(() => EmployeeTasksUpdateManyWithoutEmployeesItemsInput, {
    nullable: true,
  })
  employeeTasksItems?: EmployeeTasksUpdateManyWithoutEmployeesItemsInput;
}

export { EmployeesUpdateInput as EmployeesUpdateInput };
