/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { EmployeeProjectsCreateNestedManyWithoutEmployeesItemsInput } from "./EmployeeProjectsCreateNestedManyWithoutEmployeesItemsInput";
import { EmployeeRolesCreateNestedManyWithoutEmployeesItemsInput } from "./EmployeeRolesCreateNestedManyWithoutEmployeesItemsInput";
import { EmployeeTasksCreateNestedManyWithoutEmployeesItemsInput } from "./EmployeeTasksCreateNestedManyWithoutEmployeesItemsInput";

@InputType()
class EmployeesCreateInput {
  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => EmployeeProjectsCreateNestedManyWithoutEmployeesItemsInput,
  })
  @ValidateNested()
  @Type(() => EmployeeProjectsCreateNestedManyWithoutEmployeesItemsInput)
  @IsOptional()
  @Field(() => EmployeeProjectsCreateNestedManyWithoutEmployeesItemsInput, {
    nullable: true,
  })
  employeeProjectsItems?: EmployeeProjectsCreateNestedManyWithoutEmployeesItemsInput;

  @ApiProperty({
    required: false,
    type: () => EmployeeRolesCreateNestedManyWithoutEmployeesItemsInput,
  })
  @ValidateNested()
  @Type(() => EmployeeRolesCreateNestedManyWithoutEmployeesItemsInput)
  @IsOptional()
  @Field(() => EmployeeRolesCreateNestedManyWithoutEmployeesItemsInput, {
    nullable: true,
  })
  employeeRolesItems?: EmployeeRolesCreateNestedManyWithoutEmployeesItemsInput;

  @ApiProperty({
    required: false,
    type: () => EmployeeTasksCreateNestedManyWithoutEmployeesItemsInput,
  })
  @ValidateNested()
  @Type(() => EmployeeTasksCreateNestedManyWithoutEmployeesItemsInput)
  @IsOptional()
  @Field(() => EmployeeTasksCreateNestedManyWithoutEmployeesItemsInput, {
    nullable: true,
  })
  employeeTasksItems?: EmployeeTasksCreateNestedManyWithoutEmployeesItemsInput;
}

export { EmployeesCreateInput as EmployeesCreateInput };
