/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Incidents } from "./Incidents";
import { IncidentsCountArgs } from "./IncidentsCountArgs";
import { IncidentsFindManyArgs } from "./IncidentsFindManyArgs";
import { IncidentsFindUniqueArgs } from "./IncidentsFindUniqueArgs";
import { DeleteIncidentsArgs } from "./DeleteIncidentsArgs";
import { IncidentsService } from "../incidents.service";
@graphql.Resolver(() => Incidents)
export class IncidentsResolverBase {
  constructor(protected readonly service: IncidentsService) {}

  async _incidentsItemsMeta(
    @graphql.Args() args: IncidentsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Incidents])
  async incidentsItems(
    @graphql.Args() args: IncidentsFindManyArgs
  ): Promise<Incidents[]> {
    return this.service.incidentsItems(args);
  }

  @graphql.Query(() => Incidents, { nullable: true })
  async incidents(
    @graphql.Args() args: IncidentsFindUniqueArgs
  ): Promise<Incidents | null> {
    const result = await this.service.incidents(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Incidents)
  async deleteIncidents(
    @graphql.Args() args: DeleteIncidentsArgs
  ): Promise<Incidents | null> {
    try {
      return await this.service.deleteIncidents(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
